//! `cueforge-ai`
//!
//! AI shot planning, ghost ball aim calculation, position prediction, and safety analysis.

use cueforge_common::{Seconds, Vec2};
use cueforge_cue::{strike_cue_ball, CueStick, CueStrike};
use cueforge_physics::{BallId, World};
use cueforge_table::TableSpec;

/// Recommendation generated by the AI solver for potting a ball.
#[derive(Debug, Clone, PartialEq)]
pub struct RecommendedShot {
    pub target_ball_id: u32,
    pub pocket_index: usize,
    pub ghost_ball_position: Vec2,
    pub aim_azimuth_rad: f64,
    pub cut_angle_rad: f64,
    pub recommended_strike: CueStrike,
}

/// Defensive safety shot proposal.
#[derive(Debug, Clone, PartialEq)]
pub struct SafetyShot {
    pub target_ball_id: u32,
    pub recommended_strike: CueStrike,
    pub estimated_cue_landing: Vec2,
    pub safety_quality_score: f64,
}

/// Simulated outcome prediction for position play.
#[derive(Debug, Clone, PartialEq)]
pub struct PositionPrediction {
    pub final_cue_position: Vec2,
    pub total_ticks_simulated: u64,
    pub balls_pocketed: Vec<u32>,
}

/// Calculate ghost ball position to pot target ball into target pocket.
pub fn calculate_ghost_ball(target_pos: Vec2, pocket_pos: Vec2, ball_radius: f64) -> Vec2 {
    let pocket_dir = (pocket_pos - target_pos).normalize();
    target_pos - pocket_dir * (2.0 * ball_radius)
}

/// Simple AI solver for finding the best pot shot candidate.
pub fn find_best_shot(
    world: &World,
    table: &TableSpec,
    cue_ball_id: u32,
) -> Option<RecommendedShot> {
    let cue_ball = world.get_ball(BallId(cue_ball_id))?;
    let cue_pos = cue_ball.position.to_vec2();

    let mut best_shot = None;
    let mut min_distance = f64::MAX;

    for target in &world.balls {
        if target.id.0 == cue_ball_id || !target.is_active() {
            continue;
        }

        let target_pos = target.position.to_vec2();

        for pocket in &table.pockets {
            let ghost_pos = calculate_ghost_ball(target_pos, pocket.position, target.radius.0);

            let cue_to_ghost = ghost_pos - cue_pos;
            let aim_azimuth = cue_to_ghost.y.atan2(cue_to_ghost.x);

            let ghost_to_pocket = (pocket.position - target_pos).normalize();
            let cue_approach = cue_to_ghost.normalize();

            let cos_cut = cue_approach.dot(ghost_to_pocket).clamp(-1.0, 1.0);
            let cut_angle = cos_cut.acos();

            // Ignore extreme thin cut angles > 75 degrees (~1.3 rad)
            if cut_angle < 1.3 {
                let dist = cue_to_ghost.length() + (pocket.position - target_pos).length();
                if dist < min_distance {
                    min_distance = dist;
                    best_shot = Some(RecommendedShot {
                        target_ball_id: target.id.0,
                        pocket_index: pocket.index,
                        ghost_ball_position: ghost_pos,
                        aim_azimuth_rad: aim_azimuth,
                        cut_angle_rad: cut_angle,
                        recommended_strike: CueStrike::center_shot(2.5, aim_azimuth),
                    });
                }
            }
        }
    }

    best_shot
}

/// Predict cue ball landing position and potted balls after executing a strike.
pub fn predict_position(
    world: &World,
    strike: &CueStrike,
    cue_ball_id: u32,
    max_ticks: usize,
) -> PositionPrediction {
    let mut sim_world = world.clone();
    let cue_stick = CueStick::default();

    if let Some(cue_ball) = sim_world.get_ball_mut(BallId(cue_ball_id)) {
        strike_cue_ball(&cue_stick, strike, cue_ball);
    }

    let mut ticks = 0;
    let mut pocketed = Vec::new();

    for _ in 0..max_ticks {
        if !sim_world.is_active() && ticks > 0 {
            break;
        }
        let events = sim_world.step(Seconds(0.01));
        ticks += 1;
        for ev in events {
            if let cueforge_physics::Event::PocketCapture { ball, .. } = ev {
                pocketed.push(ball.0);
            }
        }
    }

    let final_cue_pos = sim_world
        .get_ball(BallId(cue_ball_id))
        .map(|b| b.position.to_vec2())
        .unwrap_or(Vec2::ZERO);

    PositionPrediction {
        final_cue_position: final_cue_pos,
        total_ticks_simulated: ticks,
        balls_pocketed: pocketed,
    }
}

/// Evaluate defensive safety shot options.
pub fn evaluate_safety(world: &World, _table: &TableSpec, cue_ball_id: u32) -> Option<SafetyShot> {
    let cue_ball = world.get_ball(BallId(cue_ball_id))?;
    let cue_pos = cue_ball.position.to_vec2();

    let target_ball = world
        .balls
        .iter()
        .find(|b| b.id.0 != cue_ball_id && b.is_active())?;

    let dir = (target_ball.position.to_vec2() - cue_pos).normalize();
    let aim_azimuth = dir.y.atan2(dir.x);

    // Soft defensive roll shot
    let strike = CueStrike::center_shot(0.8, aim_azimuth);
    let pred = predict_position(world, &strike, cue_ball_id, 300);

    Some(SafetyShot {
        target_ball_id: target_ball.id.0,
        recommended_strike: strike,
        estimated_cue_landing: pred.final_cue_position,
        safety_quality_score: 0.85,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use cueforge_common::{Vec2, Vec3};
    use cueforge_physics::{Ball, BallId, WorldConfig};

    #[test]
    fn test_ghost_ball_calculation() {
        let target = Vec2::new(0.0, 0.5);
        let pocket = Vec2::new(0.0, 1.0);
        let ghost = calculate_ghost_ball(target, pocket, 0.0285);
        assert!((ghost.x - 0.0).abs() < 1e-4);
        assert!((ghost.y - (0.5 - 0.057)).abs() < 1e-4);
    }

    #[test]
    fn test_position_prediction() {
        let mut world = World::new(WorldConfig::default());
        world.add_ball(Ball::new(BallId(0), Vec3::new(0.0, -0.5, 0.0)));
        world.add_ball(Ball::new(BallId(1), Vec3::new(0.0, 0.5, 0.0)));

        let strike = CueStrike::center_shot(1.5, std::f64::consts::FRAC_PI_2);
        let pred = predict_position(&world, &strike, 0, 500);

        assert!(pred.total_ticks_simulated > 0);
        assert!(pred.final_cue_position.y > -0.5);
    }
}
