//! `cueforge-ai`
//!
//! AI shot planning, ghost ball aim calculation, and difficulty estimation.

use cueforge_common::Vec2;
use cueforge_cue::CueStrike;
use cueforge_physics::World;
use cueforge_table::TableSpec;

/// Recommendation generated by the AI solver.
#[derive(Debug, Clone, PartialEq)]
pub struct RecommendedShot {
    pub target_ball_id: u32,
    pub pocket_index: usize,
    pub ghost_ball_position: Vec2,
    pub aim_azimuth_rad: f64,
    pub cut_angle_rad: f64,
    pub recommended_strike: CueStrike,
}

/// Calculate ghost ball position to pot target ball into target pocket.
pub fn calculate_ghost_ball(target_pos: Vec2, pocket_pos: Vec2, ball_radius: f64) -> Vec2 {
    let pocket_dir = (pocket_pos - target_pos).normalize();
    target_pos - pocket_dir * (2.0 * ball_radius)
}

/// Simple AI solver for finding the best pot shot candidate.
pub fn find_best_shot(
    world: &World,
    table: &TableSpec,
    cue_ball_id: u32,
) -> Option<RecommendedShot> {
    let cue_ball = world.get_ball(cueforge_physics::BallId(cue_ball_id))?;
    let cue_pos = cue_ball.position.to_vec2();

    let mut best_shot = None;
    let mut min_distance = f64::MAX;

    for target in &world.balls {
        if target.id.0 == cue_ball_id || !target.is_active() {
            continue;
        }

        let target_pos = target.position.to_vec2();

        for pocket in &table.pockets {
            let ghost_pos = calculate_ghost_ball(target_pos, pocket.position, target.radius.0);

            let cue_to_ghost = ghost_pos - cue_pos;
            let aim_azimuth = cue_to_ghost.y.atan2(cue_to_ghost.x);

            let ghost_to_pocket = (pocket.position - target_pos).normalize();
            let cue_approach = cue_to_ghost.normalize();

            let cos_cut = cue_approach.dot(ghost_to_pocket).clamp(-1.0, 1.0);
            let cut_angle = cos_cut.acos();

            // Ignore extreme thin cut angles > 75 degrees (~1.3 rad)
            if cut_angle < 1.3 {
                let dist = cue_to_ghost.length() + (pocket.position - target_pos).length();
                if dist < min_distance {
                    min_distance = dist;
                    best_shot = Some(RecommendedShot {
                        target_ball_id: target.id.0,
                        pocket_index: pocket.index,
                        ghost_ball_position: ghost_pos,
                        aim_azimuth_rad: aim_azimuth,
                        cut_angle_rad: cut_angle,
                        recommended_strike: CueStrike::center_shot(2.5, aim_azimuth),
                    });
                }
            }
        }
    }

    best_shot
}
